function net = constructResNetwork2(inputSizes,nResUnits)

net.meta.inputSize = inputSizes;
channels = 1;
kernels = 16;
net.layers = {} ;

net.layers{end+1} = struct(...
  'name', 'Start', ...
  'type', 'conv', ...
  'weights', {xavier(3,3,channels,kernels)}, ...
  'pad', 1, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;

for i = 1:nResUnits
    resLayers = resUnit.new(i);
    resBegin = resLayers{1};    
    resEnd = resLayers{2};
    %TODO: Check how to propperly initialize bn layer
    net.layers{end + 1} = resBegin;
    net.layers{end + 1} = struct(...
        'name', sprintf('bn %d 1',i'),...
        'type', 'bnorm');
    net.layers{end}.weights = {single(ones(kernels,1)),single(ones(kernels,1))};
    
    net.layers{end + 1} = struct(...
        'name', sprintf('relu %d 1',i),...
        'type', 'relu');
    
    %TODO: Check parameters for conv
    net.layers{end + 1} = struct(...
      'name', sprintf('conv %d 1',i), ...
      'type', 'conv', ...
      'weights', {xavier(3,3,kernels,kernels)}, ...
      'pad', 1, ...
      'stride', 1, ...
      'learningRate', [1 1], ...
      'weightDecay', [1 0]);

  
    net.layers{end + 1} = struct(...
        'name', sprintf('bn %d 2',i'),...
        'type', 'bnorm');
    net.layers{end}.weights = {single(ones(kernels,1)),single(ones(kernels,1))};
    
    net.layers{end + 1} = struct(...
        'name', sprintf('relu %d 2',i),...
        'type', 'relu');
    
    %TODO: Check parameters for conv
    net.layers{end + 1} = struct(...
      'name', sprintf('conv %d 2',i), ...
      'type', 'conv', ...
      'weights', {xavier(3,3,kernels,kernels)}, ...
      'pad', 1, ...
      'stride', 1, ...
      'learningRate', [1 1], ...
      'weightDecay', [1 0]);
  
    net.layers{end + 1} = resEnd;
end

net.layers{end+1} = struct(...
  'name', 'prediction', ...
  'type', 'conv', ...
  'weights', {xavier(3,3,kernels,channels)}, ...
  'pad', 1, ...
  'stride', 1, ...
  'learningRate', [1 1], ...
  'weightDecay', [1 0]) ;

net = vl_simplenn_tidy(net) ;
end
